liberaforms/views/site.py
"""
This file is part of LiberaForms.

# SPDX-FileCopyrightText: 2020 LiberaForms.org
# SPDX-License-Identifier: AGPL-3.0-or-later
"""

import os, json
import mimetypes
from feedgen.feed import FeedGenerator
from flask import g, request, render_template, redirect, Response
from flask import Blueprint, current_app, url_for
from flask import session, flash, jsonify
from flask_babel import gettext as _
import flask_login

from liberaforms.models.site import Site
from liberaforms.models.invite import Invite
from liberaforms.models.user import User
from liberaforms.models.form import Form
from liberaforms.domain.user import UserDomain
from liberaforms.utils import auth
from liberaforms.utils import sanitizers
from liberaforms.utils import validators
from liberaforms.utils import tokens
from liberaforms.utils import html_parser
from liberaforms.utils.chart_data import get_site_statistics
from liberaforms.utils.dispatcher import Dispatcher
import liberaforms.utils.wtf as wtf

from pprint import pprint

site_bp = Blueprint('site_bp', __name__,
                    template_folder='../templates/site')


@site_bp.route('/site/save-blurb', methods=['POST'])
@auth.enabled_admin_required
def save_blurb():
    if 'editor' in request.form:
        g.site.save_blurb(request.form['editor'])
        flash(_("Text saved OK"), 'success')
    return redirect(url_for('main_bp.index'))


@site_bp.route('/site/recover-password', methods=['GET', 'POST'])
@site_bp.route('/site/recover-password/<string:token>', methods=['GET'])
@auth.anonymous_user_required
@tokens.sanitized_token
def recover_password(token=None):
    if token:
        user = User.find(token=token)
        if not user:
            flash(_("Couldn't find that token"), 'warning')
            return redirect(url_for('main_bp.index'))
        if tokens.has_token_expired(user.token):
            flash(_("Your petition has expired"), 'warning')
            user.delete_token()
            return redirect(url_for('main_bp.index'))
        if user.blocked:
            user.delete_token()
            flash(_("Your account has been blocked"), 'warning')
            return redirect(url_for('main_bp.index'))
        user.delete_token()
        user.validated_email=True
        user.save()
        flask_login.login_user(user)
        return redirect(url_for('user_bp.reset_password'))

    wtform=wtf.GetEmail()
    if wtform.validate_on_submit():
        user = User.find(email=wtform.email.data, blocked=False)
        if user:
            user.save_token()
            Dispatcher().send_account_recovery(user)
        if not user and wtform.email.data == current_app.config['ROOT_USER']:
            if not User.find(email=wtform.email.data):
                # auto invite root user
                invite=Invite(  email=wtform.email.data,
                                message="New root user",
                                token=tokens.create_token(Invite),
                                role='admin',
                                invited_by_id=None)
                invite.save()
                return redirect(url_for('user_bp.create_new_user',
                                        invite=invite.token['token']))
        flash(_("We may have sent you an email"), 'info')
        return redirect(url_for('main_bp.index'))
    return render_template('recover-password.html', wtform=wtform)


@site_bp.route('/site/terms-and-conditions', methods=['GET', 'POST'])
@auth.enabled_admin_required
def edit_terms_and_conditions():
    if request.method == 'POST':
        if 'markdown' in request.form and "checkbox_text" in request.form:
            markdown=sanitizers.bleach_text(request.form['markdown'])
            if not markdown:
                markdown = _("Please accept our terms and conditions.")
            g.site.save_terms_and_conditions(
                markdown = markdown,
                html = sanitizers.markdown2HTML(markdown),
                checkbox_text = sanitizers.remove_html_tags(request.form['checkbox_text'])
            )
            flash(_("Terms and conditions saved OK"), 'success')
    return render_template('terms-and-conditions.html')


@site_bp.route('/site/toggle-terms-and-conditions', methods=['POST'])
@auth.enabled_admin_required
def toggle_terms_and_conditions():
    return jsonify({'enabled': g.site.toggle_terms_and_conditions()})


@site_bp.route('/site/data-consent', methods=['GET', 'POST'])
@auth.enabled_admin_required
def edit_data_consent():
    if request.method == 'POST':
        if 'markdown' in request.form and "checkbox_text" in request.form:
            markdown=sanitizers.bleach_text(request.form['markdown'])
            kwargs = {
                "markdown": markdown,
                "checkbox_text": sanitizers.remove_html_tags(request.form['checkbox_text']),
                "required": "True"
            }
            g.site.save_consent(kwargs)
            flash(_("GDPR text saved OK"), 'success')
    return render_template('site/data-consent.html')


@site_bp.route('/site/toggle-data-consent', methods=['POST'])
@auth.enabled_admin_required
def toggle_data_consent():
    return jsonify({'enabled': g.site.toggle_consent_enabled()})


@site_bp.route('/site/toggle-share-data-consent', methods=['POST'])
@auth.enabled_admin_required
def toggle_share_data_consent():
    return jsonify({'shared': g.site.toggle_consent_shared()})


@site_bp.route('/site/preview-new-user-form', methods=['GET'])
@auth.enabled_admin_required
def preview_new_user_form():
    return render_template('new-user.html', wtform=wtf.NewUser(), preview_only=True)


@site_bp.route('/site/change-sitename', methods=['GET', 'POST'])
@auth.enabled_admin_required
def change_name():
    if request.method == 'POST' and 'sitename' in request.form:
        g.site.name=request.form['sitename']
        g.site.save()
        flash(_("Site name changed OK"), 'success')
        return redirect(url_for('admin_bp.site_admin'))
    return render_template('change-sitename.html', site=g.site)


@site_bp.route('/site/change-default-language', methods=['GET', 'POST'])
@auth.enabled_admin_required
def change_default_language():
    if request.method == 'POST':
        if 'language' in request.form \
            and request.form['language'] in current_app.config['LANGUAGES']:
            g.site.language=request.form['language']
            g.site.save()
            flash(_("Language updated OK"), 'success')
            return redirect(url_for('admin_bp.site_admin'))
    return render_template('common/change-language.html',
                            current_language=g.site.language,
                            go_back_to_admin_panel=True)

@site_bp.route('/site/change-icon', methods=['GET', 'POST'])
@auth.enabled_admin_required
def change_icon():
    if request.method == 'POST':
        if not request.files['file']:
            flash(_("Required file is missing"), 'warning')
            return render_template('change-icon.html')
        file=request.files['file']
        if "image/" in file.content_type:
            try:
                g.site.change_favicon(file)
                flash(_("Logo changed OK. Refresh with  &lt;F5&gt;"), 'success')
                return redirect(url_for('admin_bp.site_admin'))
            except Exception as error:
                current_app.logger.error(error)
        else:
            flash(_("An image file is required"), 'warning')
            return render_template('change-icon.html')
    return render_template('change-icon.html')


@site_bp.route('/site/reset-favicon', methods=['GET'])
@auth.enabled_admin_required
def reset_site_favicon():
    if g.site.reset_favicon():
        flash(_("Logo reset OK. Refresh with  &lt;F5&gt;"), 'success')
    return redirect(url_for('admin_bp.site_admin'))


@site_bp.route('/site/edit-mimetypes', methods=['GET', 'POST'])
@auth.enabled_admin_required
def edit_mimetypes():
    wtform=wtf.FileExtensions()
    if wtform.validate_on_submit():
        mimetypes.init()
        updated_mimetypes = {"extensions":[], "mimetypes": []}
        extensions = wtform.extensions.data.splitlines()
        for extension in extensions:
            if not extension:
                continue
            mime_type = mimetypes.types_map[f".{extension}"]
            if not extension in updated_mimetypes["extensions"]:
                updated_mimetypes["extensions"].append(extension)
                updated_mimetypes["mimetypes"].append(mime_type)
        g.site.mimetypes = updated_mimetypes
        g.site.save()
        flash(_("Enabled file extensions updated OK"), 'success')
        return redirect(url_for('admin_bp.site_admin'))
    if request.method == 'GET':
        wtform.extensions.data = '\n'.join(g.site.mimetypes['extensions'])
    return render_template('edit-mimetypes.html', wtform=wtform)


@site_bp.route('/site/toggle-invitation-only', methods=['POST'])
@auth.enabled_admin_required__json
def toggle_invitation_only():
    return jsonify(invite=g.site.toggle_invitation_only())


@site_bp.route('/site/toggle-newuser-uploads-default', methods=['POST'])
@auth.enabled_admin_required__json
def toggle_newuser_uploads_default():
    return jsonify(uploads=g.site.toggle_newuser_uploads_default())


@site_bp.route('/site/primary-color', methods=['GET', 'POST'])
@auth.enabled_admin_required
def primary_color():
    wtform=wtf.ChangePrimaryColor()
    if request.method == 'GET':
        wtform.hex_color.data=g.site.primary_color
    if wtform.validate_on_submit():
        g.site.primary_color=wtform.hex_color.data
        g.site.save()
        flash(_("Color changed OK"), 'success')
        return redirect(url_for('admin_bp.site_admin'))
    return render_template('set-primary-color.html', wtform=wtform)


@site_bp.route('/site/edit-new-form-message', methods=['GET', 'POST'])
@auth.enabled_admin_required
def new_form_msg():
    wtform=wtf.NewFormMessage()
    languages = []
    for language_code, value in current_app.config['LANGUAGES'].items():

liberaforms/templates/site/change-contact-info.html
{% extends "base.html" %}
{% block content %}

<!-- change_contact_info_page -->

<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-5">
      <div class="title_1 delimited">
        {%trans%}Contact information{%endtrans%}
      </div>

      <p style="font-size: 1.15em">
      {%trans%}Tell your users how to get in touch with you.{%endtrans%}
      </p>

      <form method="POST">
        {{ wtform.csrf_token }}
        <p>
          {{ wtform.contact_info(class_="form-control", rows="7") }}
          {% for error in wtform.contact_info.errors %}
              <span class="formError">{{ error }}</span>
          {% endfor %}
        </p>
        <div class="form-actions">
          <input class="btn-success btn"
                 type="submit"
                 value="{%trans%}Save{%endtrans%}">
          <a class="btn btn-primary"
             role="button"
             href="/admin#contact_info">
            {%trans%}Cancel{%endtrans%}
          </a>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

liberaforms/templates/site/change-icon.html
{% extends "base.html" %}
{% block content %}

<!-- change_icon_page -->

<script src="/static/parsley/parsley.min.js"></script>
<script src="/static/parsley/i18n/{{ current_user.language }}.js"></script>
<link rel="stylesheet" type="text/css" href="/static/css/parsley.css">

<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-5">

      <div class="title_1 delimited">
          {%trans%}Change site icon{%endtrans%}
      </div>
      <div class="title_2">{%trans%}Upload an image{%endtrans%}</div>

      <form id="upload_form" method="POST" enctype=multipart/form-data >
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

          <span class="hint">
            {%trans%}A square image{%endtrans%}.
            {%trans%}Keep the kilobytes to a minimum{%endtrans%}
          </span>
          <div class="form-group">
            <input type=file
                   name=file
                   class="form-control"
                   data-parsley-filemimetypes="image/png, image/jpeg"
                   required=True />
          </div>

          <div class="form-actions">
            <input class="btn-success btn"
                          type="submit"
                          value="{%trans%}Upload{%endtrans%}" />
            <a class="btn btn-primary"
               role="button"
               href="/admin">
              {%trans%}Cancel{%endtrans%}
            </a>
            <a class="btn btn-outline-secondary"
               role="button"
               href="/site/reset-favicon">
               {%trans%}Use default{%endtrans%}
             </a>
          </div>
      </form>
    </div>
  </div>
</div>

<script>
$(function () {
  $('#upload_form').parsley().on('field:validated', function() {
    var ok = $('.parsley-error').length === 0;
    $('.bs-callout-info').toggleClass('hidden', !ok);
    $('.bs-callout-warning').toggleClass('hidden', ok);
  })
});
window.Parsley.addValidator('filemimetypes', {
  validateString: function(_value, requirement, parsleyInstance) {
    //console.log(requirement)
    if (!window.FormData) {
      return true;
    }
    var file = parsleyInstance.$element[0].files;
    if (file.length == 0) {
      return true;
    }
    var allowedMimeTypes = requirement.replace(/\s/g, "").split(',');
    return allowedMimeTypes.indexOf(file[0].type) !== -1;
  },
  requirementType: 'string',
  messages: {
    {{current_user.language}}: "{%trans%}Please use a PNG or JPG file{%endtrans%}"
  }
});
</script>

{% endblock %}

liberaforms/templates/site/change-new-form-msg.html
{% extends "base.html" %}
{% block content %}

<!-- change_contact_info_page -->

<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-5">
      <div class="title_1 delimited">
        {%trans%}New form message{%endtrans%}
      </div>

      <p style="font-size: 1.15em">
      {%trans%}Display this line of text when a new form is created.{%endtrans%}
      </p>

      <form method="POST">
        {{ wtform.csrf_token }}
        <p>
          {{ wtform.language.label }}<br />
          {{ wtform.language(class_="form-control") }}
          {% for error in wtform.language.errors %}
              <span class="formError">{{ error }}</span>
          {% endfor %}
        </p>
        <p>
          {{ wtform.msg.label }}<br />
          <span class="hint">{{_("May include HTML links")}}</span>
          {{ wtform.msg(class_="form-control", rows="7") }}
          {% for error in wtform.msg.errors %}
              <span class="formError">{{ error }}</span>
          {% endfor %}
          <div id="preview" style="display:none">
            <label>{%trans%}Preview{%endtrans%}</label><br />
            <span id="msg_preview" />
          </div>
        </p>
        <div class="form-actions">
          <input class="btn-success btn"
                 type="submit"
                 value="{%trans%}Save{%endtrans%}">
        </div>
      </form>
    </div>
  </div>
</div>

<script>
const messages = {{ messages | tojson}}
const previews = {{ previews | tojson}}
function setMessage(lang_code) {
  var msg = messages[lang_code] !== undefined ? messages[lang_code] : ""
  $('#msg').val(msg)
  var msg_preview = previews[lang_code] !== undefined ? previews[lang_code] : ""
  if (msg_preview !== "") {
    $('#preview').show()
  }
  $('#msg_preview').html(msg_preview)
}
$(function() {
  var language = $('#language').val()
  setMessage(language)
});
jQuery("#language").change(function(){
    var language = $('#language').val()
    setMessage(language)
});
</script>
{% endblock %}

liberaforms/templates/site/change-sitename.html
{% extends "base.html" %}
{% block content %}

<!-- change_sitename_page -->

<script src="/static/parsley/parsley.min.js"></script>
<script src="/static/parsley/i18n/{{ current_user.language }}.js"></script>
<link rel="stylesheet" type="text/css" href="/static/css/parsley.css">

<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-5">
      <div class="title_1 delimited">
        {%trans%}Change site name{%endtrans%}
      </div>

      <div class="title_2">
        {%trans%}New site name{%endtrans%}
        <span class='required'>●</span>
      </div>

      <form method="POST">
        <input type="hidden"
               name="csrf_token"
               value="{{ csrf_token() }}" />
        <p>
          <input type="text"
                 name="sitename"
                 class="form-control"
                 value="{{site.name }}"
                 required >
        </p>
        <div class="form-actions">
          <input class="btn-success btn"
                 type="submit"
                 value="{%trans%}Save{%endtrans%}">
          <a class="btn btn-primary"
             role="button"
             href="/admin">
            {%trans%}Cancel{%endtrans%}
          </a>
        </div>
      </form>
    </div>
  </div>
</div>

<script>
  $(function () {
    $('form').parsley()
  })
</script>

{% endblock %}

liberaforms/templates/site/data-consent.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      {% set consent=g.site.get_consent() %}
      {% with text=consent,
              title=_("GDPR"),
              sub_title=_("New users must agree to this text."),
              toggle_enabled_url="/site/toggle-data-consent",
              return_url="/admin#site_settings",
              default_markdown=g.site.get_default_consent().markdown,
              force_required=True %}
        {% include 'common/edit-consent.html' %}
      {% endwith %}

      <div class="title_2 delimited"
           style="margin-top:3em">
        Share this text with other users
      </div>
      {%trans%}Let users include this GDPR text in their forms.{%endtrans%}

      <div id="toggle_shared"
           class="btn-group btn-toggle"
           style="float:right">
        <button id="shared_true"
                class="btn btn-xs
                      {% if consent.shared %}
                      btn-primary
                      {% else %}
                      btn-outline-secondary
                      {% endif %}
                      ">
            {%trans%}True{%endtrans%}
        </button>
        <button id="shared_false"
                class="btn btn-xs
                      {% if not consent.shared %}
                      btn-primary
                      {% else %}
                      btn-outline-secondary
                      {% endif %}
                      ">
          {%trans%}False{%endtrans%}
        </button>
      </div>
    </div>
  </div>
</div>

<script>
  document.getElementById('toggle_shared')
          .addEventListener('click', function(evt){
    $.ajax({
      url : "{{ url_for('site_bp.toggle_share_data_consent') }}",
      type: "POST",
      dataType: "json",
      beforeSend: function(xhr, settings) {
          if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
              xhr.setRequestHeader("X-CSRFToken", csrftoken)
          }
      },
      success: function(data, textStatus, jqXHR)
      {
        if (data.shared == true) {
          $('#shared_true').addClass('btn-primary').removeClass('btn-outline-secondary');
          $('#shared_false').removeClass('btn-primary').addClass('btn-outline-secondary');
        }
        else if (data.shared == false) {
          $('#shared_true').removeClass('btn-primary').addClass('btn-outline-secondary');
          $('#shared_false').addClass('btn-primary').removeClass('btn-outline-secondary');
        }
      }
    });
  });
</script>

{% endblock %}

liberaforms/templates/site/edit-mimetypes.html
{% extends "base.html" %}
{% block content %}

<!-- edit_mimetypes_page -->

<script src="/static/parsley/parsley.min.js"></script>
<script src="/static/parsley/i18n/{{ current_user.language }}.js"></script>
<link rel="stylesheet" type="text/css" href="/static/css/parsley.css">

<div class="container">
  <div class="row">
    <div class="col-md-3"></div>

    <div class="col-md-5">
      <div class="title_1 delimited">
        {%trans%}Form attachments{%endtrans%}
      </div>
      <div class="title_text_subtext">
      {%trans%}These file types can be uploaded with the forms{%endtrans%}
      </div>

      <form method="POST">
        {{ wtform.csrf_token }}
        {{ wtform.extensions.label }} <span class='required'>●</span><br />
        {{trans}}A list of file extensions. One per line.{{endtrans}}
        {{ wtform.extensions(class_="form-control", rows="7") }}
        {% for error in wtform.extensions.errors %}
            <span class="formError">{{ error }}</span>
        {% endfor %}

        <div class="form-actions">
          <input class="btn-success btn"
                 type="submit"
                 value="{%trans%}Save{%endtrans%}">
          <a class="btn
                    btn-primary"
             role="button"
             href="/admin#site_settings">
             {%trans%}Cancel{%endtrans%}
          </a>
        </div>
      </form>

      <p>&nbsp</p>

      <div class="title_2">
        {%trans%}Enabled mimetypes{%endtrans%}
      </div>

      <table class="table table-sm">
        <tbody>
        {% for mimetype in g.site.mimetypes.mimetypes %}
          <tr>
            <td>
              {{ mimetype }}
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

<script>
$(function () {
  $('form').parsley().on('form:validate', function() {
    $('span[class=formError]').remove()
  })
})
</script>

{% endblock %}

liberaforms/templates/site/ldap-test.html
{% extends "base.html" %}
{% block content %}

<!-- ldap_test_page -->

<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">

      <div class="title_1 delimited">
          {%trans%}LDAP{%endtrans%}
      </div>
      <div class="title_2">
        {%trans%}Configuration{%endtrans%}
      </div>
      <table class="table table-sm">
        <tr>
          <td>Server</td>
          <td>{{ config['LDAP_SERVER'] }}</td>
        </tr>
      </table>
      <div class="title_3">
        {%trans%}Authentification{%endtrans%}
      </div>
      <table class="table table-sm">
        <tr>
          <td>Bind account</td>
          <td>
            {% if config['LDAP_ANONYMOUS_BIND'] %}
              <span class="hint">Anonymous bind</span>
            {% elif config['LDAP_BIND_ACCOUNT'] %}
              {{ config['LDAP_BIND_ACCOUNT'] }}
            {% endif %}
          </td>
        </tr>
        <tr>
          <td>Bind password</td>
          <td>
            {% if config['LDAP_ANONYMOUS_BIND'] %}
              <span class="hint">Anonymous bind</span>
            {% elif config['LDAP_BIND_PASSWORD'] %}
              ***********
            {% endif %}
          </td>
        </tr>
        <tr>
          <td>
            User DN {% if config['LDAP_USER_DN_LIST']|length > 1 %}list{% endif %}
          </td>
          <td>
            {% for dn in config['LDAP_USER_DN_LIST'] %}
              {{ dn }}<br />
            {% endfor %}
          </td>
        </tr>
      </table>
      <div class="title_3">
        {%trans%}Authorization{%endtrans%}
      </div>
      <table class="table table-sm">
        <tr>
          <td>Search base</td>
          <td>{{ config['LDAP_SEARCH_BASE_DN'] }}</td>
        </tr>
        <tr>
          <td>
            Filter
            <button class="btn btn-primary btn-xs"
                    onclick="js:show_filter_editor()">
               {%trans%}Edit{%endtrans%}
            </button>
          </td>
          <td>
            <span id="saved_filter">
              {{ g.site.get_ldap_filter() }}
            </span>
          </td>
        </tr>
        <tr id="ldap_filter_editor" style="display:none;">
          <td colspan="2">
            <button class="btn btn-primary btn-xs mt-3"
                    onclick="js:save_filter()">
              {%trans%}Save{%endtrans%}
            </button>
            <button class="btn btn-danger btn-xs mt-3"
                    onclick="js:reset_filter()">
              {# i18n: verb. This is a button #}
              {%trans%}Reset{%endtrans%}
            </button>
            <button class="btn btn-outline-secondary btn-xs mt-3"
                    onclick="js:$('#ldap_filter_editor').hide()">
              {%trans%}Cancel{%endtrans%}
            </button>
            <div class="mt-3">
              Use this filter to search for LiberaForms users in the DIT
              <span id="filter_error" class="formError"></span>
              <textarea id="ldap_filter_input"
                        class="form-control"
                        rows="3">
              </textarea>
            </div>
          </td>
        </tr>
      </table>
      <div class="title_2 delimited">
        {%trans%}Tests{%endtrans%}
      </div>
      <textarea id="test_result"
                rows="3"
                class="form-control"
                disabled >Test results are displayed here</textarea>

      <div class="mt-2">
        {%trans%}Test authentification{%endtrans%}
      </div>
      <div class="form-inline">
      	<div class="form-group mr-2">
          <input id="ldap_username"
                 class="form-control"
                 type="text"
                 placeholder="{%trans%}Username{%endtrans%}" />
      	</div>
      	<div class="form-group mr-2">
          <input id="ldap_password"
                class="form-control"
                type="password"
                placeholder="{%trans%}Password{%endtrans%}" />
      	</div>
      	<div class="form-group text-right">
          <button class="btn btn-primary"
                  onclick="js:bind(this)">
              Bind
          </button>
      	</div>
      </div>
      <div class="hint">
      {% if config['LDAP_BIND_ACCOUNT'] %}
        Leave empty to test the bind account
      {% else %}
        Leave empty to test anonymous bind
      {% endif %}
      </div>
      <div class="mt-2">
        {%trans%}Test authorization{%endtrans%}
      </div>
      <div class="form-inline">
      	<div class="form-group mr-2">
          <input id="search_text"
                 class="form-control"
                 type="text"
                 name="uid"
                 autocomplete="on"
                 placeholder="%uid" />
      	</div>
      	<div class="form-group text-right">
          <button class="btn btn-primary"
                  onclick="js:search(this)">
              {%trans%}Filter{%endtrans%}
          </button>
      	</div>
    </div>
  </div>
</div>


<script>
function show_filter_editor() {
  $('#filter_error').html("")
  $('#ldap_filter_input').val($('#saved_filter').text().trim())
  $('#ldap_filter_editor').show()
}
function save_filter() {
  var filter = $('#ldap_filter_input').val().trim()
  $.ajax({
    url : "{{ url_for('site_bp.ldap_edit_filter') }}",
    type: "POST",
    dataType: "json",
    data: {
      'filter': filter
    },
    beforeSend: function(xhr, settings) {
      if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
        xhr.setRequestHeader("X-CSRFToken", csrftoken)
      }
    },
    success: function(data, textStatus, jqXHR)
    {
      if (data.error !== undefined) {
        $('#filter_error').html(data.error)
      } else {
        $('#ldap_filter_editor').hide()
        $('#saved_filter').text(data.filter)
      }
    }
  });
}
function reset_filter() {
  $.ajax({
    url : "{{ url_for('site_bp.ldap_reset_filter') }}",
    type: "POST",
    dataType: "json",
    beforeSend: function(xhr, settings) {
      if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
        xhr.setRequestHeader("X-CSRFToken", csrftoken)
      }
    },
    success: function(data, textStatus, jqXHR)
    {
      if (data.error !== undefined) {
        $('#filter_error').html(data.error)
      } else {
        $('#ldap_filter_editor').hide()
        $('#saved_filter').text(data.filter)
      }
    }
  });
}
function bind(button_el) {
  $('#test_result').val("")
  $.ajax({
    url : "{{ url_for('site_bp.ldap_test_bind') }}",
    type: "POST",
    dataType: "json",
    data: {
      'username': $('#ldap_username').val(),
      'password': $('#ldap_password').val()
    },
    beforeSend: function(xhr, settings) {
      if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
        xhr.setRequestHeader("X-CSRFToken", csrftoken)
      }
    },
    success: function(data, textStatus, jqXHR)
    {
      console.log(data.result)
      $('#test_result').val(parse_results(data.result))
    }
  });
}
function search(button_el) {
  $('#test_result').val("")
  $.ajax({
    url : "{{ url_for('site_bp.ldap_test_search') }}",
    type: "POST",
    dataType: "json",
    data: {
      'username': $('#ldap_username').val(),
      'password': $('#ldap_password').val(),
      'param': $('#search_text').val()
    },
    beforeSend: function(xhr, settings) {
      if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
        xhr.setRequestHeader("X-CSRFToken", csrftoken)
      }
    },
    success: function(data, textStatus, jqXHR)
    {
      $('#test_result').val(parse_results(data.result))
    }
  });
}
function parse_results(data) {
  var result=""
  for (let key in data){
    if (data[key].constructor == Object) {
      for (let obj_key in data[key]){
        result = result+obj_key+": "+data[key][obj_key]+'\n'
      }
    }else{
      result = result+key+": "+data[key]+'\n'
    }
  }
  return result.replace(/\n*$/, "")
}
</script>

{% endblock %}

liberaforms/templates/site/terms-and-conditions.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      {% with text=g.site.terms_and_conditions,
              title=_("Terms and conditions"),
              sub_title=_("New users must agree to these terms and conditions"),
              toggle_enabled_url="/site/toggle-terms-and-conditions",
              return_url="/admin#site_settings",
              force_required=True %}
        {% include 'common/edit-consent.html' %}
      {% endwith %}
    </div>
  </div>
</div>

{% endblock %}